services:
  - type: web
    name: my-app
    env: docker
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      # Add other environment variables as needed
